CREATE DATABASE IF NOT EXISTS telkom_profile
 CHARACTER SET utf8mb4
 COLLATE utf8mb4_unicode_ci;

USE telkom_profile;

CREATE TABLE IF NOT EXISTS program_studi (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 nama VARCHAR(120) NOT NULL,
 jenjang VARCHAR(20) NOT NULL,
 deskripsi TEXT NOT NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS berita (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 judul VARCHAR(180) NOT NULL,
 ringkasan VARCHAR(300) NOT NULL,
 isi TEXT NOT NULL,
 tanggal_publish DATE NOT NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS pesan (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 nama VARCHAR(100) NOT NULL,
 email VARCHAR(120) NOT NULL,
 pesan TEXT NOT NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;